# (Remove "version: ..." to avoid the Compose v2 warning)
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_microservices_db
    ports:
      - "3308:3306"  # example: using port 3308 on host
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d


  user-service:
    build:
      context: .               # <--- Build context is the ROOT
      dockerfile: user-service/Dockerfile
    container_name: user-service
    depends_on:
      - mysql
    environment:
      MYSQL_DSN: "root:root@tcp(mysql_db:3306)/go_microservices_db"
      SERVICE_PORT: "8081"
    ports:
      - "8081:8081"

  order-service:
    build:
      context: .               # <--- Build context is the ROOT
      dockerfile: order-service/Dockerfile
    container_name: order-service
    depends_on:
      - mysql
    environment:
      MYSQL_DSN: "root:root@tcp(mysql_db:3306)/go_microservices_db"
      SERVICE_PORT: "8082"
    ports:
      - "8082:8082"

volumes:
  mysql_data:
